config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "logs#index"
  resources :logs, except: :show
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  has_many_attached :images
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :logs, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy

  validates :name, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :avatar])
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  def index
    @logs = Log.order("date DESC").page(params[:page]).per(5)
  end

  def new
    @log = Log.new
  end

  def edit
  end

  def create
    if Log.create(log_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    #削除ボタンを押された写真のidを取ってきて、一つずつ削除する。
    unless params[:log][:image_ids].nil?
      params[:log][:image_ids].each do |image_id|
        image = @log.images.find(image_id)
        image.purge
      end
    end
    if @log.update(log_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @log.destroy
    redirect_to root_path
  end

  private
    def set_log
      @log = Log.find(params[:id])
    end

    def log_params
      params.require(:log).permit(:place, :date, :point, :member, :En, :Ex, :Dt, :Max, :Ave, :Cl, :Temp, :fish, images: []).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @logs = @user.logs.page(params[:page]).per(5).order("date DESC")
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bluelog2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/_form.html.erb
<div class="form">
<%= form_with(model: log, local: true) do |form| %>
  <% if log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>
      <ul>
      <% log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-row">
    <div class="form-group col-5">
      <%= form.label :place, "場所：" %>
      <%= form.text_field :place %>
    </div>

    <div class="form-group col-6">
      <%= form.label :date, "日付：" %>
      <%= form.date_select :date %>
    </div>

    <div class="form-group col-12 top-space">
      <%= form.label :point, "ポイント名：" %>
      <%= form.text_field :point %>
    </div>
  </div>

  <div class="form-group top-space">
    <%= form.label :member, "メンバー" %>
    <%= form.text_area :member, class: "form-control", id: "inputAddress2", placeholder: "" %>
  </div>

  <div class="form-row mt-5">
    <div class="form-group col-4">
      <%= form.label :En, "En :" %>
      <%= form.time_select :En %>
    </div>

    <div class="form-group col-4 flex">
      <%= form.label :Max, "Max :" %>
      <%= form.text_field :Max, size: 5 %>
      <div>m</div>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-4">
      <%= form.label :Ex, "Ex :" %>
      <%= form.time_select :Ex %>
    </div>
    <div class="form-group col-4 flex">
      <%= form.label :Ave, "Ave :" %>
      <%= form.text_field :Ave, size: 5 %>
      <div>m</div>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col flex">
      <%= form.label :Dt, "Dt :" %>
      <%= form.number_field :Dt, size: 5 %>
      <div>分</div>
    </div>

    <div class="form-group col flex">
      <%= form.label :Cl, "Cl :" %>
      <%= form.number_field :Cl, size: 5 %>
      <div>m</div>
    </div>

    <div class="form-group col flex">
      <%= form.label :Temp, "水温 :" %>
      <%= form.text_field :Temp, size: 5 %>
      <div>℃</div>
    </div>
  </div>

  <div class="form-row">
  </div>


  <div class="form-group mt-5">
    <%= form.label :fish, "見た魚" %>
    <%= form.text_area :fish, class: "form-control", id: "inputAddress2", placeholder: "" %>
  </div>

  <div class="field mt-5">
    <%= form.label :images, "写真を追加：" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <% if log.images.attached? %>
    <div class="image-flex">
      <% num = 0 %>
      <% log.images.each do |image| %>
        <% num += 1 %>
        <div class="left-space images">
          <%= image_tag image, class: "image top-space", size: "100x100" %>
          <%= form.label :"image_ids_#{image.id}", class: "btn-circle-flat" do %>x
            <%= form.check_box :image_ids, {multiple: true, class: "hidden"}, image.id, false %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="actions mt-5">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/logs/_header.html.erb
<nav class="navbar navbar-expand-lg bg-info">
  <div class="container text-white">
    <a class="navbar-brand text-white" id="bluelog" href="/">BlueLog</a>
    <% if user_signed_in? %>
      <% if current_page?(root_path) %>
        <p class="my-auto mx-auto header-text header-left-space"><%= current_user.name%>さん こんにちは</p>
      <% end %>
      <% if current_page?(new_log_path) %>
        <p class="my-auto mx-auto header-text header-left-space">ログ作成</p>
      <% end %>
      <% if @log %>
        <% if @log.user_id && current_page?(edit_log_path(@log)) %>
          <p class="my-auto mx-auto header-text header-left-space">ログ編集</p>
        <% end %>
      <% end %>
      <% if current_page?(edit_user_path(current_user)) %>
        <p class="my-auto mx-auto header-text header-left-space">プロフィール編集</p>
      <% end %>
    <% end %>
    <% if @user %>
      <% if @user.id && current_page?(user_path(@user)) %>
        <p class="my-auto mx-auto header-text header-left-space"><%= @user.name%>さんのログ一覧</p>
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'ログ作成', new_log_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            アカウント
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'マイログ', user_path(current_user), class: "dropdown-item text-dark"%>
              <%= link_to 'プロフィール編集', edit_user_path(current_user), class: "dropdown-item text-dark"%>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item text-dark" %>
          </div>
        </li>
      </ul>
    <%= link_to '魚図鑑', "https://zukan.com/fish/internal4851", class: "fish-book text-white", target: :_blank %>
    <% else %>
      <% if current_page?(new_user_session_path) %>
        <div class="sign-in">
          <p class="my-auto mx-auto header-text">ログイン</p>
        </div>
        <%= link_to '新規登録', new_user_registration_path, class: "nav-link text-white" %>
      <% elsif current_page?(new_user_registration_path) %>
        <div class="sign-in">
          <p class="my-auto mx-auto header-text">新規登録</p>
        </div>
        <%= link_to 'ログイン', new_user_session_path, class: "nav-link text-white" %>
      <% else %>
        <div class="nav-item flex right">
          <%= link_to 'ログイン', new_user_session_path, class: "nav-link text-white" %>
          <%= link_to '新規登録', new_user_registration_path, class: "nav-link text-white" %>
          <%= link_to '魚図鑑', "https://zukan.com/fish/internal4851", class: "fish-book text-white", target: :_blank %>
        </div>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/logs/_log.html.erb
<div class="my-4 d-flex justify-content-center">
  <div class="card" style="width: 50%;">
    <div class="card-body">
      <div class="row">
        <%= link_to "#{log.user.name}", user_path(log.user), class: "user-name" %>
        <% if log.user.avatar.attached? %>
          <%= image_tag log.user.avatar, size: "40x40", class: "avatar" %>
        <% end %>
        <h6 class="card-subtitle mb-2 text-muted ml-auto mr-4"><%= log.date.strftime("%m/%d") %></h6>
      </div>
      <div class="row bottom-space">
        <h5 class="card-title m-auto font-weight-bold"><%= log.place %></h5>
      </div>
      <p class="card-text">ポイント名：<%= log.point %></p>
      <p class="mt-3">メンバー：<%= log.member %></p>
      <div class="row">
        <p class="col-4">En : <%= log.En.strftime("%H：%M") %></p>
        <p class="col-4">Max : <%= log.Max %> m</p>
      </div>
      <div class="row">
        <p class="col-4">Ex : <%= log.Ex.strftime("%H：%M") %></p>
        <p class="col-4">Ave : <%= log.Ave %> m</p>
      </div>
      <div class="row">
        <p class="col">Dt : <%= log.Dt %> 分</p>
        <p class="col">Cl : <%= log.Cl %> m</p>
        <p class="col">水温：<%= log.Temp %> ℃</p>
      </div>
      <p class="mt-3">見た魚：<%= log.fish %></p>
      <% if log.images.attached? %>
        <p class="mt-3">写真</p>
        <% log.images.each do |image| %>
          <%= image_tag image, class: "image", size: "105x105" %>
        <% end %>
      <% end %>
      <% if user_signed_in? && current_user.id == log.user_id %>
        <%= link_to '削除', log, class: "btn btn-primary float-right ml-2", id: "delete-btn", method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>
        <%= link_to '編集', edit_log_path(log), class: "btn btn-primary float-right", id: "edit-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/logs/edit.html.erb
<%= render 'header' %>
<%= render 'form', log: @log %>

app/views/logs/index.html.erb
<%= render 'header' %>
<%= render @logs %>
<div class="float-right mr-4">
  <%= paginate(@logs) %>
</div>

app/views/logs/new.html.erb
<%= render 'header' %>
<%= render 'form', log: @log %>

app/views/users/edit.html.erb
<%= render "logs/header" %>
<div class="edit-acount">
<%= form_with(model: current_user, local: true) do |form| %>

  <div class="edit-acount-name">
    <%= form.label :name, "名前：" %>
    <%= form.text_field :name, class: "edit-acount-form" %>
  </div>

  <p class="avatar-text">現在のプロフィール写真</p>
  <% if current_user.avatar.attached? %>
    <%= image_tag current_user.avatar, size: "120x120", class: "edit-avatar-image" %>
  <% else %>
    <p class="center">設定無し</p>
  <% end %>

  <div class="edit-acount-avatar">
    <%= form.label :avatar, "プロフィール写真：", class: "avatar-label" do %>写真を変更
      <%= form.file_field :avatar, class: "hidden edit-avatar" %>
    <% end %>
  </div>

  <div class="edit-acount-submit-btm">
    <%= form.submit %>
  </div>

<% end %>
</div>

app/views/users/show.html.erb
<%= render 'logs/header' %>
<%= render partial: "logs/log", collection: @logs, as: "log" %>
<div class="float-right mr-4">
  <%= paginate(@logs) %>
</div>